version: '3'

services:
  db:
    container_name: expenses-db
    image: mysql:5.6
    ports:
    - "9999:3306"
    volumes: 
    - ./.data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    logging:
      driver: json-file
      options: 
        max-size: "200k"